# Generated by Django 4.0.4 on 2023-10-17 07:02

import blog.models
from django.db import migrations, models
import django.db.models.deletion
import utils.constraint_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(default=blog.models.next_number, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('blog_type', models.PositiveSmallIntegerField(choices=[(0, 'blog'), (1, 'privacy'), (2, 't&c')], default=1)),
                ('removed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RelatedBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
                ('related_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_blog', to='blog.blog')),
            ],
            options={
                'verbose_name': 'related blog',
                'verbose_name_plural': 'related blogs',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', utils.constraint_fields.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='blog-media/')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
            options={
                'verbose_name': 'blog media',
                'verbose_name_plural': 'blog media',
            },
        ),
    ]
