# Generated by Django 4.0.4 on 2023-10-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'blog'), (1, 'privacy'), (2, 't&c')], default=0),
        ),
    ]
