# Generated by Django 4.0.4 on 2023-10-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('info_type', models.PositiveSmallIntegerField(choices=[(0, 'privacy'), (1, 't&c')], default=0)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 't&c',
                'verbose_name_plural': 't&c',
            },
        ),
    ]
