# Generated by Django 4.0.4 on 2023-10-01 06:29

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='campaign', max_length=30, null=True)),
                ('file', models.FileField(upload_to='email-files/')),
                ('completed', models.BooleanField(default=False)),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('failed_emails', models.TextField(max_length=4000)),
                ('error', models.TextField(max_length=4000)),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('scheduled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmailCampaignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=350)),
                ('use_ssl', models.BooleanField(default=True)),
                ('port', models.SmallIntegerField(default=465)),
                ('email', encrypted_model_fields.fields.EncryptedEmailField()),
                ('password', encrypted_model_fields.fields.EncryptedCharField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField(max_length=10000)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
