# Generated by Django 4.0.4 on 2023-10-01 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailcampaigntemplate',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automail.emailcampaign'),
        ),
        migrations.AddField(
            model_name='emailcampaigntemplate',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automail.emailconfiguration'),
        ),
        migrations.AddField(
            model_name='emailcampaigntemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automail.emailtemplate'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='follow_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automail.emailcampaign'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
