# Generated by Django 4.0.4 on 2023-10-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automail', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
