# Generated by Django 4.0.4 on 2023-10-01 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automail', '0003_emailtemplate_attachment_emailtemplate_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='attachment',
        ),
        migrations.CreateModel(
            name='EmailTemplateAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='attachments/')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automail.emailtemplate')),
            ],
        ),
    ]
