# Generated by Django 4.0.4 on 2023-10-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automail', '0004_remove_emailtemplate_attachment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='template',
            new_name='body',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
