# Generated by Django 4.0.4 on 2023-10-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automail', '0005_rename_template_emailtemplate_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='email_lookup',
            field=models.CharField(default='Email', max_length=150),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='signature',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='variables',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
