# Generated by Django 4.0.4 on 2023-10-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automail', '0006_emailcampaign_email_lookup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(default='Sample Template', max_length=50),
        ),
    ]
