# Generated by Django 4.0.4 on 2023-10-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automail', '0009_alter_emailconfiguration_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='email_send_rule',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Respond for all'), (1, 'Reply for not responded'), (2, 'Reply for responded')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='save_to_inbox',
            field=models.BooleanField(default=True),
        ),
    ]
