# Generated by Django 4.0.4 on 2023-10-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automail', '0010_emailcampaign_email_send_rule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='copy_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
