# Generated by Django 4.0.4 on 2023-10-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automail', '0011_emailtemplate_copy_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcampaign',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='email_send_rule',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='error',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='failed_count',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='failed_emails',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='follow_up',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='scheduled',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='sent_count',
        ),
        migrations.AddField(
            model_name='emailcampaigntemplate',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailcampaigntemplate',
            name='created_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emailcampaigntemplate',
            name='email_send_rule',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Respond for all'), (1, 'Reply for not responded'), (2, 'Reply for responded')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaigntemplate',
            name='error',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaigntemplate',
            name='failed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaigntemplate',
            name='failed_emails',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaigntemplate',
            name='is_followup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailcampaigntemplate',
            name='schedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaigntemplate',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailcampaigntemplate',
            name='sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
