# Generated by Django 4.0.4 on 2023-10-11 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automail', '0012_remove_emailcampaign_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcampaigntemplate',
            name='is_followup',
        ),
        migrations.AddField(
            model_name='emailcampaigntemplate',
            name='followup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automail.emailcampaigntemplate'),
        ),
    ]
