# Generated by Django 4.0.4 on 2023-10-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automail', '0013_remove_emailcampaigntemplate_is_followup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaigntemplate',
            name='smtp_error_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
