# Generated by Django 4.0.4 on 2023-10-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automail', '0015_emailcampaign_discontinued_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfiguration',
            name='imap_host',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='host',
            field=models.CharField(max_length=255),
        ),
    ]
