# Generated by Django 4.0.4 on 2023-10-15 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automail', '0016_emailconfiguration_imap_host_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedEmailDomains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator])),
            ],
        ),
    ]
